name:               accelerate-tensorflow-lite
version:            0.1.0.0
github:             "tmcdonell/accelerate-tensorflow"
license:            BSD3
author:             "Trevor L. McDonell"
maintainer:         "Trevor L. McDonell <trevor.mcdonell@gmail.com>"
copyright:          "2021 The Accelerate Team"

extra-source-files:
- ../README.md
- ../CHANGELOG.md
- cbits/edgetpu.*
- converter.py

# Metadata used when publishing your package
synopsis:           Accelerate backend component generating TensorFlow graphs
category:           Accelerate, Concurrency, Data, Parallelism

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Please see the README on GitHub at <https://github.com/tmcdonell/accelerate-tensorflow#readme>

dependencies:
- base                          >= 4.7 && < 5
- accelerate                    == 1.3.*
- accelerate-tensorflow
- bytestring
- deepseq
- directory
- filepath
- formatting
- lens-family
- mtl
- process
- proto-lens
- random
- tensorflow
- tensorflow-proto
- text
- vector

library:
  source-dirs: src
  cxx-sources: cbits/edgetpu.cc

  exposed-modules:
    - Data.Array.Accelerate.TensorFlow.Lite

  ghc-options:
    - -Wall
    - -O2

  cc-options:
    -O3
    -Wall
    -march=native

  extra-libraries:
      stdc++
      clog
      cpuinfo
      edgetpu
      farmhash
      tensorflow-lite
      ruy
      XNNPACK
      flatbuffers
      pthreadpool
      fft2d_fftsg
      fft2d_fftsg2d

tests:
  operation-unit-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -O2
    dependencies:
      - accelerate-tensorflow
      - hedgehog
      - tasty

# vim: nospell
